import { CheckCircle2, Clock3, FileText, Pencil, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'
import { Button } from '../components/Button'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { PriorityBadge } from '../components/PriorityBadge'
import { useAppStore } from '../hooks/useAppStore'
import { formatDate, formatMinutes, isOverdue } from '../utils/date'
import { calculatePriority, getPriorityExplanation } from '../utils/priority'

export function ActivityDetailsPage() {
  const { id } = useParams(); const { activities, updateActivity, deleteActivity } = useAppStore(); const activity = activities.find((item) => item.id === id); const navigate = useNavigate(); const [confirming, setConfirming] = useState(false); if (!activity) return <Navigate to="/atividades" replace />
  const selectedActivity = activity
  const score = calculatePriority(activity); const currentStatus = activity.status !== 'Concluída' && isOverdue(activity.dueDate) ? 'Atrasada' : activity.status
  function complete() { updateActivity(selectedActivity.id, { name: selectedActivity.name, subject: selectedActivity.subject, description: selectedActivity.description, type: selectedActivity.type, dueDate: selectedActivity.dueDate, difficulty: selectedActivity.difficulty, importance: selectedActivity.importance, estimatedMinutes: selectedActivity.estimatedMinutes, status: 'Concluída', notes: selectedActivity.notes }) }
  return <div className="animate-fade-in"><PageHeader back title="Detalhes" action={<Link aria-label="Editar atividade" to={`/atividades/${activity.id}/editar`} className="rounded-xl bg-brand-50 p-2.5 text-brand-700"><Pencil size={18} /></Link>} /><div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-brand-700">{activity.type}{activity.subject ? ` · ${activity.subject}` : ''}</p><h2 className="mt-2 text-xl font-extrabold tracking-tight text-slate-900">{activity.name}</h2></div><PriorityBadge score={score} /></div><p className="mt-4 text-sm leading-6 text-slate-600">{activity.description || 'Nenhuma descrição informada.'}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-slate-100 pt-4"><div><p className="text-xs text-slate-400">Prazo</p><p className={`mt-1 text-sm font-bold ${isOverdue(activity.dueDate) && activity.status !== 'Concluída' ? 'text-rose-600' : 'text-slate-700'}`}>{formatDate(activity.dueDate, { day: '2-digit', month: 'long', year: 'numeric' })}</p></div><div><p className="text-xs text-slate-400">Tempo estimado</p><p className="mt-1 text-sm font-bold text-slate-700">{formatMinutes(activity.estimatedMinutes)}</p></div><div><p className="text-xs text-slate-400">Dificuldade</p><p className="mt-1 text-sm font-bold text-slate-700">{activity.difficulty} de 5</p></div><div><p className="text-xs text-slate-400">Status</p><p className="mt-1 text-sm font-bold text-slate-700">{currentStatus}</p></div></div></div><section className="mt-5 rounded-2xl bg-brand-50 p-4"><p className="text-sm font-bold text-brand-900">Como a prioridade foi definida</p><p className="mt-1.5 text-sm leading-6 text-brand-800">{getPriorityExplanation(activity)}</p></section>{activity.notes && <section className="mt-5"><h3 className="section-title">Observações</h3><p className="mt-2 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{activity.notes}</p></section>}<div className="mt-7 space-y-3">{activity.status !== 'Concluída' && <Button onClick={complete} className="w-full"><CheckCircle2 size={17} /> Marcar como concluída</Button>}<Button variant="ghost" onClick={() => setConfirming(true)} className="w-full text-rose-600 hover:bg-rose-50"><Trash2 size={17} /> Excluir atividade</Button></div>{confirming && <Modal title="Excluir atividade?" onClose={() => setConfirming(false)}><p className="text-sm leading-6 text-slate-600">Esta ação removerá a atividade permanentemente deste dispositivo.</p><div className="mt-5 flex gap-3"><Button variant="secondary" onClick={() => setConfirming(false)} className="flex-1">Cancelar</Button><Button variant="danger" onClick={() => { deleteActivity(activity.id); navigate('/atividades') }} className="flex-1">Excluir</Button></div></Modal>}</div>
}
