import { ChevronLeft, ChevronRight, CalendarDays } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { EmptyState } from '../components/EmptyState'
import { PageHeader } from '../components/PageHeader'
import { useAppStore } from '../hooks/useAppStore'
import { formatDate } from '../utils/date'

type EventItem = { id: string; date: string; name: string; kind: 'Atividade' | 'Projeto'; href: string }
const week = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S']
function monthLabel(date: Date) { return new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(date) }
function dateKey(year: number, month: number, day: number) { return `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}` }
export function CalendarPage() {
  const { activities, projects } = useAppStore(); const [month, setMonth] = useState(() => { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), 1) }); const [selected, setSelected] = useState<string | null>(null)
  const events = useMemo<EventItem[]>(() => [...activities.map((activity) => ({ id: activity.id, date: activity.dueDate, name: activity.name, kind: 'Atividade' as const, href: `/atividades/${activity.id}` })), ...projects.map((project) => ({ id: project.id, date: project.dueDate, name: project.name, kind: 'Projeto' as const, href: `/projetos/${project.id}` }))], [activities, projects])
  const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const leading = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); const cells = Array.from({ length: leading + days }, (_, index) => index < leading ? null : index - leading + 1); const selectedEvents = selected ? events.filter((item) => item.date === selected) : []
  return <div className="animate-fade-in"><PageHeader title="Calendário" subtitle="Todos os prazos em um só lugar." />{!events.length ? <EmptyState icon={CalendarDays} title="Nenhum evento cadastrado." description="Atividades e projetos com prazo aparecerão aqui." /> : <><section className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><button aria-label="Mês anterior" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100"><ChevronLeft size={19} /></button><h2 className="text-sm font-extrabold capitalize text-slate-800">{monthLabel(month)}</h2><button aria-label="Próximo mês" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100"><ChevronRight size={19} /></button></div><div className="grid grid-cols-7 gap-y-2 text-center">{week.map((day, index) => <span key={`${day}-${index}`} className="pb-1 text-[10px] font-bold text-slate-400">{day}</span>)}{cells.map((day, index) => { if (!day) return <span key={`space-${index}`} />; const key = dateKey(month.getFullYear(), month.getMonth(), day); const hasEvents = events.some((item) => item.date === key); const today = new Date().toISOString().slice(0,10) === key; const active = selected === key; return <button key={key} onClick={() => setSelected(key)} aria-label={`${day} de ${monthLabel(month)}`} className={`relative mx-auto flex h-9 w-9 items-center justify-center rounded-xl text-xs font-semibold transition ${active ? 'bg-brand-600 text-white' : today ? 'bg-brand-50 text-brand-700' : 'text-slate-600 hover:bg-slate-100'}`}>{day}{hasEvents && <span className={`absolute bottom-1 h-1 w-1 rounded-full ${active ? 'bg-white' : 'bg-brand-600'}`} />}</button>})}</div></section><section className="mt-6"><h2 className="section-title">{selected ? formatDate(selected, { day: '2-digit', month: 'long' }) : 'Selecione uma data'}</h2>{selected ? selectedEvents.length ? <div className="mt-3 space-y-2">{selectedEvents.map((item) => <Link to={item.href} key={`${item.kind}-${item.id}`} className="flex items-center justify-between rounded-xl border border-slate-100 bg-white p-3.5 shadow-sm transition hover:shadow-md"><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-700">{item.name}</p><p className="mt-0.5 text-xs text-slate-500">{item.kind} · prazo</p></div><ChevronRight size={18} className="text-slate-300" /></Link>)}</div> : <p className="mt-3 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma atividade para este dia.</p> : <p className="mt-3 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Toque em uma data para visualizar os eventos.</p>}</section></>}</div>
}
