import { ArrowRight, BellRing, CalendarDays, CheckCircle2, ClipboardPlus, FolderKanban, ListChecks, TrendingUp } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { ActivityCard } from '../components/ActivityCard'
import { Button } from '../components/Button'
import { EmptyState } from '../components/EmptyState'
import { PageHeader } from '../components/PageHeader'
import { useAppStore } from '../hooks/useAppStore'
import { formatDate, isOverdue } from '../utils/date'
import { getAlerts } from '../utils/alerts'
import { calculatePriority } from '../utils/priority'

export function DashboardPage() {
  const { currentUser, activities, projects, updateActivity } = useAppStore(); const navigate = useNavigate()
  const active = activities.filter((activity) => activity.status !== 'Concluída'); const completed = activities.filter((activity) => activity.status === 'Concluída'); const overdue = active.filter((activity) => isOverdue(activity.dueDate)); const sorted = [...active].sort((a, b) => calculatePriority(b) - calculatePriority(a)); const focus = sorted.slice(0, 3); const alerts = getAlerts(activities, projects); const ongoingProjects = projects.filter((project) => project.steps.some((step) => !step.completed)); const percentage = activities.length ? Math.round((completed.length / activities.length) * 100) : 0
  return <div className="animate-fade-in"><PageHeader title={`Olá, ${currentUser?.name.split(' ')[0] ?? ''}`} subtitle={activities.length ? 'Seu plano de estudos está atualizado.' : 'Seu espaço está pronto.'} action={<button aria-label="Ver alertas" onClick={() => document.getElementById('alerts')?.scrollIntoView({ behavior: 'smooth' })} className="rounded-xl bg-brand-50 p-2.5 text-brand-700 hover:bg-brand-100"><BellRing size={19} /></button>} />
    {!activities.length ? <EmptyState icon={ClipboardPlus} title="Você ainda não possui atividades." description="Adicione sua primeira atividade para começar a organizar seus estudos." actionLabel="Nova atividade" onAction={() => navigate('/atividades/nova')} /> : <>
      <section className="rounded-2xl bg-brand-600 p-5 text-white shadow-lg shadow-brand-100"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-violet-100">Resumo do dia</p><p className="mt-2 text-3xl font-extrabold">{focus.length} foco{focus.length !== 1 ? 's' : ''}</p><p className="mt-1 text-sm text-violet-100">para avançar no que mais importa</p></div><CalendarDays className="text-violet-200" size={25} /></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-white transition-all" style={{ width: `${percentage}%` }} /></div><p className="mt-2 text-xs font-semibold text-violet-100">{percentage}% das atividades concluídas</p></section>
      <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="section-title">Foco de hoje</h2><Link className="flex items-center gap-1 text-xs font-bold text-brand-700" to="/atividades">Ver todas <ArrowRight size={13} /></Link></div>{focus.length ? <div className="space-y-2.5">{focus.map((activity) => <ActivityCard key={activity.id} activity={activity} onComplete={(item) => updateActivity(item.id, { name: item.name, subject: item.subject, description: item.description, type: item.type, dueDate: item.dueDate, difficulty: item.difficulty, importance: item.importance, estimatedMinutes: item.estimatedMinutes, status: 'Concluída', notes: item.notes })} />)}</div> : <EmptyState icon={ListChecks} title="Você não possui tarefas para hoje." description="Quando houver atividades, as mais importantes aparecerão aqui." />}</section>
      <section className="mt-7 grid grid-cols-2 gap-3"><Link to="/atividades" className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm transition hover:shadow-md"><p className="text-2xl font-extrabold text-slate-800">{active.length}</p><p className="mt-1 text-xs font-medium text-slate-500">Pendentes</p></Link><Link to="/atividades?prazo=atrasadas" className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm transition hover:shadow-md"><p className={`text-2xl font-extrabold ${overdue.length ? 'text-rose-600' : 'text-slate-800'}`}>{overdue.length}</p><p className="mt-1 text-xs font-medium text-slate-500">Atrasadas</p></Link></section>
      {ongoingProjects.length > 0 && <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="section-title">Projetos em andamento</h2><Link className="text-xs font-bold text-brand-700" to="/projetos">Ver projetos</Link></div><div className="space-y-2">{ongoingProjects.slice(0, 2).map((project) => { const total = project.steps.length; const done = project.steps.filter((step) => step.completed).length; const progress = total ? Math.round(done / total * 100) : 0; return <Link to={`/projetos/${project.id}`} key={project.id} className="block rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className="flex justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-800">{project.name}</p><p className="mt-0.5 text-xs text-slate-500">Prazo {formatDate(project.dueDate)}</p></div><span className="text-sm font-extrabold text-brand-700">{progress}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-600" style={{ width: `${progress}%` }} /></div></Link>})}</div></section>}
      {alerts.length > 0 && <section id="alerts" className="mt-7 scroll-mt-4"><h2 className="mb-3 section-title">Alertas inteligentes</h2><div className="space-y-2">{alerts.map((alert) => <Link to={alert.href ?? '/'} key={alert.id} className={`block rounded-2xl border p-3.5 transition hover:shadow-sm ${alert.tone === 'danger' ? 'border-rose-100 bg-rose-50' : alert.tone === 'warning' ? 'border-amber-100 bg-amber-50' : 'border-sky-100 bg-sky-50'}`}><div className="flex gap-3"><TrendingUp size={18} className={alert.tone === 'danger' ? 'text-rose-600' : alert.tone === 'warning' ? 'text-amber-600' : 'text-sky-600'} /><div><p className="text-sm font-bold text-slate-800">{alert.title}</p><p className="mt-0.5 text-xs leading-5 text-slate-600">{alert.description}</p></div></div></Link>)}</div></section>}
    </>}
    {activities.length > 0 && <Button onClick={() => navigate('/atividades/nova')} className="mt-7 w-full"><ClipboardPlus size={17} /> Nova atividade</Button>}
  </div>
}
