import { FormEvent, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Button } from '../components/Button'
import { PageHeader } from '../components/PageHeader'
import { useAppStore } from '../hooks/useAppStore'
import type { Difficulty, Importance, SchoolProject } from '../types'
import { toInputDate } from '../utils/date'

const emptyForm = { name: '', subject: '', description: '', dueDate: toInputDate(), difficulty: 3 as Difficulty, importance: 3 as Importance, steps: [], members: [] }
export function ProjectFormPage() {
  const { id } = useParams(); const { projects, data, addProject, updateProject } = useAppStore(); const existing = projects.find((item) => item.id === id); const navigate = useNavigate(); const [form, setForm] = useState<Omit<SchoolProject, 'id' | 'ownerId' | 'createdAt' | 'updatedAt'>>(existing ? ({ name: existing.name, subject: existing.subject, description: existing.description, dueDate: existing.dueDate, difficulty: existing.difficulty, importance: existing.importance, steps: existing.steps, members: existing.members }) : emptyForm); const [error, setError] = useState('')
  const change = <K extends keyof typeof form>(key: K, value: typeof form[K]) => setForm((previous) => ({ ...previous, [key]: value }))
  function submit(event: FormEvent) { event.preventDefault(); if (!form.name.trim()) return setError('Informe o nome do projeto.'); if (!form.dueDate) return setError('Informe um prazo válido.'); if (existing) { updateProject(existing.id, form); navigate(`/projetos/${existing.id}`) } else { const created = addProject(form); navigate(`/projetos/${created}`) } }
  return <div className="animate-fade-in"><PageHeader back title={existing ? 'Editar projeto' : 'Novo projeto'} subtitle="Depois, divida o projeto em etapas menores." /><form onSubmit={submit} className="space-y-4"><label className="block"><span className="field-label">Nome do projeto *</span><input required value={form.name} onChange={(event) => change('name', event.target.value)} className="field-input" placeholder="Como você quer identificar este projeto?" /></label><label className="block"><span className="field-label">Matéria</span><input list="project-subjects" value={form.subject} onChange={(event) => change('subject', event.target.value)} className="field-input" placeholder="Informe ou crie uma matéria" /><datalist id="project-subjects">{data.subjects.map((subject) => <option key={subject} value={subject} />)}</datalist></label><label className="block"><span className="field-label">Prazo *</span><input required type="date" value={form.dueDate} onChange={(event) => change('dueDate', event.target.value)} className="field-input" /></label><div className="grid grid-cols-2 gap-3"><label><span className="field-label">Dificuldade</span><select value={form.difficulty} onChange={(event) => change('difficulty', Number(event.target.value) as Difficulty)} className="field-input">{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} de 5</option>)}</select></label><label><span className="field-label">Importância</span><select value={form.importance} onChange={(event) => change('importance', Number(event.target.value) as Importance)} className="field-input">{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} de 5</option>)}</select></label></div><label className="block"><span className="field-label">Descrição</span><textarea rows={4} value={form.description} onChange={(event) => change('description', event.target.value)} className="field-input resize-none" /></label><p className="rounded-xl bg-brand-50 p-3 text-xs leading-5 text-brand-800">Após salvar, você poderá adicionar etapas e integrantes, caso seja um projeto em grupo.</p>{error && <p role="alert" className="field-error">{error}</p>}<div className="flex gap-3 pt-2"><Button type="button" variant="secondary" className="flex-1" onClick={() => navigate(-1)}>Cancelar</Button><Button type="submit" className="flex-1">Salvar projeto</Button></div></form></div>
}
