import { ArrowDown, ArrowUp, Check, ChevronRight, Pencil, Plus, Trash2, UserPlus, Users } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'
import { Button } from '../components/Button'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { useAppStore } from '../hooks/useAppStore'
import type { ProjectMember, ProjectStep, SchoolProject } from '../types'
import { formatDate } from '../utils/date'

const projectInput = (project: SchoolProject) => ({ name: project.name, subject: project.subject, description: project.description, dueDate: project.dueDate, difficulty: project.difficulty, importance: project.importance, steps: project.steps, members: project.members })
export function ProjectDetailsPage() {
  const { id } = useParams(); const { projects, updateProject, deleteProject } = useAppStore(); const project = projects.find((item) => item.id === id); const navigate = useNavigate(); const [stepTitle, setStepTitle] = useState(''); const [member, setMember] = useState({ name: '', assignedTask: '', status: 'Pendente' as ProjectMember['status'] }); const [modal, setModal] = useState<'step' | 'member' | 'delete' | null>(null); const [editingStep, setEditingStep] = useState<ProjectStep | null>(null)
  if (!project) return <Navigate to="/projetos" replace />
  const selectedProject: SchoolProject = project
  const sortedSteps = [...project.steps].sort((a,b) => a.order - b.order); const done = sortedSteps.filter((step) => step.completed).length; const progress = sortedSteps.length ? Math.round(done / sortedSteps.length * 100) : 0
  function saveSteps(steps: ProjectStep[]) { updateProject(selectedProject.id, { ...projectInput(selectedProject), steps }) }
  function saveMembers(members: ProjectMember[]) { updateProject(selectedProject.id, { ...projectInput(selectedProject), members }) }
  function submitStep(event: FormEvent) { event.preventDefault(); if (!stepTitle.trim()) return; if (editingStep) saveSteps(selectedProject.steps.map((step) => step.id === editingStep.id ? { ...step, title: stepTitle.trim() } : step)); else saveSteps([...selectedProject.steps, { id: crypto.randomUUID(), title: stepTitle.trim(), completed: false, order: selectedProject.steps.length }]); setStepTitle(''); setEditingStep(null); setModal(null) }
  function submitMember(event: FormEvent) { event.preventDefault(); if (!member.name.trim()) return; saveMembers([...selectedProject.members, { id: crypto.randomUUID(), name: member.name.trim(), assignedTask: member.assignedTask.trim(), status: member.status }]); setMember({ name: '', assignedTask: '', status: 'Pendente' }); setModal(null) }
  function reorder(step: ProjectStep, direction: -1 | 1) { const index = sortedSteps.findIndex((item) => item.id === step.id); const replacement = sortedSteps[index + direction]; if (!replacement) return; const reordered = sortedSteps.map((item) => item.id === step.id ? { ...item, order: replacement.order } : item.id === replacement.id ? { ...item, order: step.order } : item); saveSteps(reordered) }
  return <div className="animate-fade-in"><PageHeader back title="Projeto" action={<Link aria-label="Editar projeto" to={`/projetos/${project.id}/editar`} className="rounded-xl bg-brand-50 p-2.5 text-brand-700"><Pencil size={18} /></Link>} /><section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-brand-700">{project.subject || 'Sem matéria'}</p><h2 className="mt-2 text-xl font-extrabold tracking-tight text-slate-900">{project.name}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{project.description || 'Nenhuma descrição informada.'}</p><div className="mt-5 flex items-end justify-between"><div><p className="text-xs text-slate-400">Prazo</p><p className="mt-1 text-sm font-bold text-slate-700">{formatDate(project.dueDate, { day: '2-digit', month: 'long', year: 'numeric' })}</p></div><p className="text-2xl font-extrabold text-brand-700">{progress}%</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-600 transition-all duration-500" style={{ width: `${progress}%` }} /></div></section>
    <section className="mt-7"><div className="mb-3 flex items-center justify-between"><div><h2 className="section-title">Etapas</h2><p className="mt-0.5 text-xs text-slate-500">{sortedSteps.length ? `${done} concluída${done !== 1 ? 's' : ''} de ${sortedSteps.length}` : 'Divida este projeto em partes menores.'}</p></div><button onClick={() => { setEditingStep(null); setStepTitle(''); setModal('step') }} className="rounded-lg bg-brand-50 p-2 text-brand-700" aria-label="Adicionar etapa"><Plus size={18} /></button></div>{sortedSteps.length ? <div className="space-y-2">{sortedSteps.map((step, index) => <div key={step.id} className="flex items-center gap-2 rounded-xl border border-slate-100 bg-white p-3 shadow-sm"><button aria-label={step.completed ? 'Marcar etapa como pendente' : 'Concluir etapa'} onClick={() => saveSteps(project.steps.map((item) => item.id === step.id ? { ...item, completed: !item.completed } : item))} className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full border ${step.completed ? 'border-brand-600 bg-brand-600 text-white' : 'border-slate-300 text-transparent hover:border-brand-500'}`}><Check size={14} /></button><p className={`min-w-0 flex-1 text-sm font-semibold ${step.completed ? 'text-slate-400 line-through' : 'text-slate-700'}`}>{step.title}</p><div className="flex shrink-0 text-slate-400"><button disabled={index === 0} onClick={() => reorder(step, -1)} aria-label="Mover etapa para cima" className="rounded p-1 disabled:opacity-30 hover:bg-slate-100"><ArrowUp size={15} /></button><button disabled={index === sortedSteps.length - 1} onClick={() => reorder(step, 1)} aria-label="Mover etapa para baixo" className="rounded p-1 disabled:opacity-30 hover:bg-slate-100"><ArrowDown size={15} /></button><button onClick={() => { setEditingStep(step); setStepTitle(step.title); setModal('step') }} aria-label="Editar etapa" className="rounded p-1 hover:bg-slate-100"><Pencil size={14} /></button><button onClick={() => saveSteps(project.steps.filter((item) => item.id !== step.id))} aria-label="Excluir etapa" className="rounded p-1 text-rose-500 hover:bg-rose-50"><Trash2 size={14} /></button></div></div>)}</div> : <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-5 text-center"><p className="text-sm font-bold text-slate-700">Nenhuma etapa criada.</p><p className="mt-1 text-xs leading-5 text-slate-500">Adicione a primeira etapa para acompanhar o progresso.</p><button onClick={() => setModal('step')} className="mt-3 text-sm font-bold text-brand-700">Adicionar etapa</button></div>}</section>
    <section className="mt-7"><div className="mb-3 flex items-center justify-between"><div><h2 className="section-title">Integrantes</h2><p className="mt-0.5 text-xs text-slate-500">Opcional para projetos em grupo.</p></div><button onClick={() => setModal('member')} className="rounded-lg bg-brand-50 p-2 text-brand-700" aria-label="Adicionar integrante"><UserPlus size={18} /></button></div>{project.members.length ? <div className="space-y-2">{project.members.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-white p-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-brand-100 text-xs font-extrabold text-brand-700">{item.name.slice(0,1).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-700">{item.name}</p><p className="truncate text-xs text-slate-500">{item.assignedTask || 'Sem tarefa atribuída'}</p></div><select aria-label={`Status de ${item.name}`} value={item.status} onChange={(event) => saveMembers(project.members.map((memberItem) => memberItem.id === item.id ? { ...memberItem, status: event.target.value as ProjectMember['status'] } : memberItem))} className="max-w-28 rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-[11px] font-semibold text-slate-600"><option>Pendente</option><option>Em andamento</option><option>Concluída</option></select><button onClick={() => saveMembers(project.members.filter((memberItem) => memberItem.id !== item.id))} aria-label={`Remover ${item.name}`} className="rounded p-1 text-rose-500 hover:bg-rose-50"><Trash2 size={15} /></button></div>)}</div> : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhum integrante adicionado.</p>}</section><Button variant="ghost" onClick={() => setModal('delete')} className="mt-8 w-full text-rose-600 hover:bg-rose-50"><Trash2 size={17} /> Excluir projeto</Button>
    {modal === 'step' && <Modal title={editingStep ? 'Editar etapa' : 'Adicionar etapa'} onClose={() => setModal(null)}><form onSubmit={submitStep}><label><span className="field-label">Nome da etapa</span><input autoFocus required value={stepTitle} onChange={(event) => setStepTitle(event.target.value)} className="field-input" /></label><div className="mt-5 flex gap-3"><Button type="button" variant="secondary" onClick={() => setModal(null)} className="flex-1">Cancelar</Button><Button type="submit" className="flex-1">Salvar</Button></div></form></Modal>}{modal === 'member' && <Modal title="Adicionar integrante" onClose={() => setModal(null)}><form onSubmit={submitMember} className="space-y-4"><label><span className="field-label">Nome *</span><input autoFocus required value={member.name} onChange={(event) => setMember({ ...member, name: event.target.value })} className="field-input" /></label><label><span className="field-label">Tarefa atribuída</span><input value={member.assignedTask} onChange={(event) => setMember({ ...member, assignedTask: event.target.value })} className="field-input" /></label><label><span className="field-label">Status</span><select value={member.status} onChange={(event) => setMember({ ...member, status: event.target.value as ProjectMember['status'] })} className="field-input"><option>Pendente</option><option>Em andamento</option><option>Concluída</option></select></label><Button type="submit" className="w-full">Adicionar integrante</Button></form></Modal>}{modal === 'delete' && <Modal title="Excluir projeto?" onClose={() => setModal(null)}><p className="text-sm leading-6 text-slate-600">As etapas e integrantes deste projeto também serão removidos permanentemente.</p><div className="mt-5 flex gap-3"><Button variant="secondary" onClick={() => setModal(null)} className="flex-1">Cancelar</Button><Button variant="danger" onClick={() => { deleteProject(project.id); navigate('/projetos') }} className="flex-1">Excluir</Button></div></Modal>}</div>
}
