import { BarChart3, CheckCircle2, Clock3, FolderKanban, ListTodo } from 'lucide-react'
import { EmptyState } from '../components/EmptyState'
import { PageHeader } from '../components/PageHeader'
import { useAppStore } from '../hooks/useAppStore'
import { isOverdue } from '../utils/date'

export function StatisticsPage() {
  const { activities, projects } = useAppStore(); if (!activities.length && !projects.length) return <div className="animate-fade-in"><PageHeader back title="Estatísticas" subtitle="Acompanhe a evolução da sua organização." /><EmptyState icon={BarChart3} title="Suas estatísticas aparecerão aqui." description="Cadastre e conclua atividades para visualizar sua evolução." /></div>
  const completed = activities.filter((item) => item.status === 'Concluída').length; const pending = activities.length - completed; const overdue = activities.filter((item) => item.status !== 'Concluída' && isOverdue(item.dueDate)).length; const ongoing = projects.filter((project) => project.steps.length ? project.steps.some((step) => !step.completed) : true).length; const percentage = activities.length ? Math.round(completed / activities.length * 100) : 0; const bySubject = activities.filter((item) => item.subject.trim()).reduce<Record<string, number>>((all, item) => ({ ...all, [item.subject]: (all[item.subject] ?? 0) + 1 }), {}); const byType = activities.reduce<Record<string, number>>((all, item) => ({ ...all, [item.type]: (all[item.type] ?? 0) + 1 }), {}); const maxSubject = Math.max(...Object.values(bySubject), 1); const maxType = Math.max(...Object.values(byType), 1)
  return <div className="animate-fade-in"><PageHeader back title="Estatísticas" subtitle="Baseado apenas no que você cadastrou." /><div className="grid grid-cols-2 gap-3"><Metric icon={CheckCircle2} value={completed} label="Concluídas" /><Metric icon={ListTodo} value={pending} label="Pendentes" /><Metric icon={Clock3} value={overdue} label="Atrasadas" danger={overdue > 0} /><Metric icon={FolderKanban} value={ongoing} label="Projetos em andamento" /></div><section className="mt-6 rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-end justify-between"><div><h2 className="section-title">Evolução da organização</h2><p className="mt-1 text-sm text-slate-500">Atividades concluídas</p></div><p className="text-3xl font-extrabold text-brand-700">{percentage}%</p></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-600 transition-all duration-500" style={{ width: `${percentage}%` }} /></div><p className="mt-3 text-xs leading-5 text-slate-500">{completed} de {activities.length} atividade{activities.length !== 1 ? 's' : ''} foram concluída{activities.length !== 1 ? 's' : ''}.</p></section>{Object.keys(bySubject).length > 0 && <Distribution title="Atividades por matéria" values={bySubject} max={maxSubject} />}{Object.keys(byType).length > 0 && <Distribution title="Atividades por tipo" values={byType} max={maxType} />}</div>
}
function Metric({ icon: Icon, value, label, danger = false }: { icon: typeof CheckCircle2; value: number; label: string; danger?: boolean }) { return <div className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><Icon size={18} className={danger ? 'text-rose-600' : 'text-brand-700'} /><p className={`mt-4 text-2xl font-extrabold ${danger ? 'text-rose-600' : 'text-slate-800'}`}>{value}</p><p className="mt-1 text-xs leading-4 text-slate-500">{label}</p></div> }
function Distribution({ title, values, max }: { title: string; values: Record<string, number>; max: number }) { return <section className="mt-6 rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="section-title">{title}</h2><div className="mt-4 space-y-3">{Object.entries(values).sort((a,b) => b[1] - a[1]).map(([label, value]) => <div key={label}><div className="flex justify-between gap-3 text-xs"><span className="truncate font-semibold text-slate-600">{label}</span><span className="font-bold text-slate-700">{value}</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-500" style={{ width: `${value / max * 100}%` }} /></div></div>)}</div></section> }
